# Generated by Django 3.1.2 on 2020-10-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addatt', '0002_auto_20201013_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attcsv',
            old_name='Ip_address',
            new_name='IP_address',
        ),
    ]
