# Generated by Django 3.1.2 on 2020-10-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addatt', '0003_auto_20201013_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attcsv',
            old_name='description',
            new_name='Description',
        ),
    ]
